USE vrg09;

INSERT INTO `ARTIST` (`ArtistID`,`LastName`,`FirstName`,`Nationality`,`DateOfBirth`,`DateDeceased`) VALUES (20,"Mills","Kalia","Morocco",1859,1917);
INSERT INTO `ARTIST` (`ArtistID`,`LastName`,`FirstName`,`Nationality`,`DateOfBirth`,`DateDeceased`) VALUES (21,"Christensen","Quinlan","El Salvador",1875,1903);
INSERT INTO `ARTIST` (`ArtistID`,`LastName`,`FirstName`,`Nationality`,`DateOfBirth`,`DateDeceased`) VALUES (22,"Blevins","Keaton","United Arab Emirates",1873,1939);
INSERT INTO `ARTIST` (`ArtistID`,`LastName`,`FirstName`,`Nationality`,`DateOfBirth`,`DateDeceased`) VALUES (23,"Sharp","Igor","South Africa",1871,1917);
INSERT INTO `ARTIST` (`ArtistID`,`LastName`,`FirstName`,`Nationality`,`DateOfBirth`,`DateDeceased`) VALUES (24,"Fischer","Oprah","Saint Kitts and Nevis",1870,1933);
INSERT INTO `ARTIST` (`ArtistID`,`LastName`,`FirstName`,`Nationality`,`DateOfBirth`,`DateDeceased`) VALUES (25,"Lawson","Hamilton","Virgin Islands, British",1864,1951);
INSERT INTO `ARTIST` (`ArtistID`,`LastName`,`FirstName`,`Nationality`,`DateOfBirth`,`DateDeceased`) VALUES (26,"Velez","Melanie","Cyprus",1882,1924);
INSERT INTO `ARTIST` (`ArtistID`,`LastName`,`FirstName`,`Nationality`,`DateOfBirth`,`DateDeceased`) VALUES (27,"Spencer","Mary","Saint Martin",1884,1932);
INSERT INTO `ARTIST` (`ArtistID`,`LastName`,`FirstName`,`Nationality`,`DateOfBirth`,`DateDeceased`) VALUES (28,"Hampton","Germane","Croatia",1856,1931);
INSERT INTO `ARTIST` (`ArtistID`,`LastName`,`FirstName`,`Nationality`,`DateOfBirth`,`DateDeceased`) VALUES (29,"Crosby","Ronan","Benin",1856,1933);
INSERT INTO `ARTIST` (`ArtistID`,`LastName`,`FirstName`,`Nationality`,`DateOfBirth`,`DateDeceased`) VALUES (30,"Ryan","Gil","Sweden",1868,1914);
INSERT INTO `ARTIST` (`ArtistID`,`LastName`,`FirstName`,`Nationality`,`DateOfBirth`,`DateDeceased`) VALUES (31,"Hickman","Chester","Guatemala",1871,1934);
INSERT INTO `ARTIST` (`ArtistID`,`LastName`,`FirstName`,`Nationality`,`DateOfBirth`,`DateDeceased`) VALUES (32,"Robles","Mercedes","Burundi",1873,1927);
INSERT INTO `ARTIST` (`ArtistID`,`LastName`,`FirstName`,`Nationality`,`DateOfBirth`,`DateDeceased`) VALUES (33,"Carlson","Madison","Puerto Rico",1876,1907);
INSERT INTO `ARTIST` (`ArtistID`,`LastName`,`FirstName`,`Nationality`,`DateOfBirth`,`DateDeceased`) VALUES (34,"Leonard","Adrian","Belgium",1866,1916);
INSERT INTO `ARTIST` (`ArtistID`,`LastName`,`FirstName`,`Nationality`,`DateOfBirth`,`DateDeceased`) VALUES (35,"Brock","Roanna","Sudan",1883,1912);
INSERT INTO `ARTIST` (`ArtistID`,`LastName`,`FirstName`,`Nationality`,`DateOfBirth`,`DateDeceased`) VALUES (36,"Boyer","Marny","Netherlands",1879,1905);
INSERT INTO `ARTIST` (`ArtistID`,`LastName`,`FirstName`,`Nationality`,`DateOfBirth`,`DateDeceased`) VALUES (37,"Moon","Leilani","Rwanda",1882,1935);
INSERT INTO `ARTIST` (`ArtistID`,`LastName`,`FirstName`,`Nationality`,`DateOfBirth`,`DateDeceased`) VALUES (38,"Martin","Britanni","Germany",1858,1921);
INSERT INTO `ARTIST` (`ArtistID`,`LastName`,`FirstName`,`Nationality`,`DateOfBirth`,`DateDeceased`) VALUES (39,"Herring","Patricia","Nepal",1867,1903);
